### ISSUE TITLE
Route [login] not defined.

### ISSUE THREAD

**Issue by prasnala** [rxcod9/joy-voyager-laravel-demo#40]
I install joy-voyager-laravel-demo as per information given on link https://github.com/rxcod9/joy-voyager-laravel-demo procedure. I got many errors but I solved that by searching online. At end I got one error "Route [login] not defined."

Online also I got one solution from other developer https://bestofphp.com/repo/rxcod9-joy-voyager-api-php-rest-api . His installation also give same error Route [login] not defined.

As per my understanding There is not route for /admin/login . Please help how to solve this issue.

**Comment by rxcod9** [comment]
@prasnala Which PHP version are you using?
Can you share where do you see this error?
